pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                // Pull the code from the repository
                git url: 'https://github.com/MaryamMairaj123/jenkinsbasic', branch: 'main'
            }
        }
        stage('Build') {
            steps {
                // Compile the Java program
                sh 'javac HelloWorld.java'
            }
        }
        stage('Run') {
            steps {
                // Run the compiled Java program
                sh 'java HelloWorld'
            }
        }
    }
}
